Bangpound\Atom\DataBundle\Entity\Category:
    type: entity
    table: category
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        term:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        scheme:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        label:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
