services:
    bangpound_atom_data.entity_manager:
        class: Doctrine\ODM\CouchDB\DocumentManager
        factory_service: doctrine
        factory_method: getManager
        arguments: ['%bangpound_atom_data.model_manager_name%']
