Bangpound\Atom\DataBundle\Entity\Feed:
    type: entity
    table: feed
    repositoryClass: Bangpound\Atom\DataBundle\Entity\FeedRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    manyToMany:
        entries:
            targetEntity: Bangpound\Atom\DataBundle\Entity\Entry
            cascade:
                - persist
                - merge
            mappedBy: feeds
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
