Bangpound\Atom\DataBundle\Entity\Link:
    type: entity
    table: link
    repositoryClass: Bangpound\Atom\DataBundle\Entity\FeedRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        title:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        rel:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        href:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        type:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        hreflang:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        length:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
