<?php

namespace Bangpound\Atom\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends EntityRepository
{
    public function findByAtomId($id, array $orderBy = null, $limit = null, $offset = null)
    {
        $criteria = array('atomId' => $id);
        $entity = $this->findOneBy($criteria, $orderBy, $limit, $offset);
        return $entity;
    }
}
